config/routes.rb
Rails.application.routes.draw do
  get 'flats', to: 'flats#index', as: :flats
  get 'flats/:id', to: 'flats#show', as: :flat
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"
require 'json'

class FlatsController < ApplicationController
  url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
  FLATS = JSON.parse(open(url).read).freeze

  def index
    @flats = FLATS
  end

  def show
    id = params[:id].to_i
    @flat = FLATS.find { |flat| flat["id"] == id }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<ul>
  <% @flats.each do |flat| %>
    <li class="list"><%= link_to flat["name"], flat_path(flat["id"]) %></li>
  <% end %>
</ul>

app/views/flats/show.html.erb
<h1><%= @flat["name"] %></h1>
<img src="<%= @flat["imageUrl"] %>" width="800" alt="">
<p>Price: <%= @flat["price"] %> <%= @flat["priceCurrency"] %> </p>

<%= link_to "Back", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>